### PR TITLE
Implementation of Ignition 2.1

### PR DESCRIPTION
**Pull request by mcuadros**
This is the implementation using ignition 2.1.

New resources:
`ignition_directory`
`ignition_link`

Updated resources:
`ignition_config`
`ignition_filesystem`
`ignition_systemd_unit`
`ignition_user`

Fixes https://github.com/terraform-providers/terraform-provider-ignition/issues/8

### CODE REVIEW

**Comment by grubernaut** [comment]
@mcuadros going to trust you've done due diligence here, as it falls on you to maintain this afterwards 😂 , however would you mind adding a comment with the acceptance test output for the provider? Thanks!

**Comment by mcuadros** [comment]
This provider doesn't have any acceptance test, since only generates a JSON string.

**Comment by s-urbaniak** [comment]
@mcuadros thanks a lot for the PR! I gave it a shot locally, and have (so far) just one suggestion, namely to mark `enable` as deprecated:
```
diff --git a/ignition/resource_ignition_systemd_unit.go b/ignition/resource_ignition_systemd_unit.go
index 3cd2511..ef6de1d 100644
--- a/ignition/resource_ignition_systemd_unit.go
+++ b/ignition/resource_ignition_systemd_unit.go
@@ -15,6 +15,13 @@ func resourceSystemdUnit() *schema.Resource {
                                Required: true,
                                ForceNew: true,
                        },
+                       "enable": {
+                               Type:       schema.TypeBool,
+                               Optional:   true,
+                               Default:    true,
+                               ForceNew:   true,
+                               Deprecated: "Use enabled instead",
+                       },
                        "enabled": {
                                Type:     schema.TypeBool,
                                Optional: true,
@@ -95,6 +102,9 @@ func buildSystemdUnit(d *schema.ResourceData, c *cache) (string, error) {
        }
 
        enabled := d.Get("enabled").(bool)
+       if e, ok := d.GetOk("enable"); ok {
+               enabled = e.(bool)
+       }
 
        return c.addSystemdUnit(&types.Unit{
                Name:     d.Get("name").(string),
```

**Comment by mcuadros** [comment]
@s-urbaniak the changes are massive, on several resources, so I rather not having any deprecated as the `create` in filesystem, since we are tagging the current master, in order to having two available versions, one for 2.0 and other for 2.1.

**Comment by s-urbaniak** [comment]
@mcuadros sounds good! if two separate versions are going to be available, then that is a viable approach.

Thanks again!

**Comment by s-urbaniak** [comment]
@mcuadros another litmus test. ignition failed on during installed with the following error:

```
[    3.319521] ignition[392]: Ignition v0.17.2
[    3.321707] ignition[392]: no config URL provided
[    3.324588] ignition[392]: failed to fetch config: unsupported config version
```

This fixes it on top of this PR:
```
diff --git a/ignition/resource_ignition_config.go b/ignition/resource_ignition_config.go
index 7f20943..7677854 100644
--- a/ignition/resource_ignition_config.go
+++ b/ignition/resource_ignition_config.go
@@ -173,6 +173,10 @@ func buildIgnition(d *schema.ResourceData) (types.Ignition, error) {
        var err error
 
        i := types.Ignition{}
+       i.Version = "2.1.0"
+       if report := i.Validate(); len(report.Entries) > 0 {
+               return i, fmt.Errorf("validation failed: %v", report.Entries)
+       }
 
        rr := d.Get("replace.0").(map[string]interface{})
        if len(rr) != 0 {
```

**Comment by grubernaut** [comment]
Test Output: 
```
$ go test -v ./ignition/...
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestValidateUnit
--- PASS: TestValidateUnit (0.00s)
=== RUN   TestIngnitionFileReplace
--- PASS: TestIngnitionFileReplace (0.02s)
=== RUN   TestIngnitionFileAppend
--- PASS: TestIngnitionFileAppend (0.02s)
=== RUN   TestIngnitionFileReplaceNoVerification
--- PASS: TestIngnitionFileReplaceNoVerification (0.02s)
=== RUN   TestIngnitionFileAppendNoVerification
--- PASS: TestIngnitionFileAppendNoVerification (0.02s)
=== RUN   TestIgnitionConfigDisks
--- PASS: TestIgnitionConfigDisks (0.03s)
=== RUN   TestIgnitionConfigArrays
--- PASS: TestIgnitionConfigArrays (0.03s)
=== RUN   TestIgnitionConfigFilesystems
--- PASS: TestIgnitionConfigFilesystems (0.03s)
=== RUN   TestIgnitionConfigFiles
--- PASS: TestIgnitionConfigFiles (0.03s)
=== RUN   TestIgnitionConfigSystemd
--- PASS: TestIgnitionConfigSystemd (0.03s)
=== RUN   TestIgnitionConfigNetworkd
--- PASS: TestIgnitionConfigNetworkd (0.03s)
=== RUN   TestIgnitionConfigUsers
--- PASS: TestIgnitionConfigUsers (0.03s)
=== RUN   TestIgnitionConfigGroupss
--- PASS: TestIgnitionConfigGroupss (0.03s)
=== RUN   TestIngnitionDirectory
--- PASS: TestIngnitionDirectory (0.03s)
=== RUN   TestIngnitionDisk
--- PASS: TestIngnitionDisk (0.03s)
=== RUN   TestIngnitionDiskResource
--- PASS: TestIngnitionDiskResource (0.03s)
=== RUN   TestIngnitionFile
--- PASS: TestIngnitionFile (0.04s)
=== RUN   TestIngnitionFilesystem
--- PASS: TestIngnitionFilesystem (0.04s)
=== RUN   TestIngnitionGroup
--- PASS: TestIngnitionGroup (0.04s)
=== RUN   TestIngnitionLink
--- PASS: TestIngnitionLink (0.03s)
=== RUN   TestIngnitionNetworkdUnit
--- PASS: TestIngnitionNetworkdUnit (0.03s)
=== RUN   TestIngnitionRaid
--- PASS: TestIngnitionRaid (0.03s)
=== RUN   TestIngnitionSystemdUnit
--- PASS: TestIngnitionSystemdUnit (0.03s)
=== RUN   TestIngnitionSystemdUnitEmptyContentWithDropIn
--- PASS: TestIngnitionSystemdUnitEmptyContentWithDropIn (0.03s)
=== RUN   TestIgnitionSystemdUnit_emptyContent
--- PASS: TestIgnitionSystemdUnit_emptyContent (0.03s)
=== RUN   TestIngnitionUser
--- PASS: TestIngnitionUser (0.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ignition/ignition	0.779s
```

**Comment by grubernaut** [comment]
@mcuadros this ready to be merged now?

**Pull request merged**
