### PR TITLE
Migration to TF 0.12 SDK

### PR DESCRIPTION
**Pull request by alexsomesan**
This change adapts the provider to use TF SDK from current tip of master.

Adaptations done:
* bump SDK
* fix test configurations for conformity to TF 0.12

Other changes:
* rename datasource config functions to reflect datasource

Tests output
```
------------------------------------------------------------
~/workspace/terraform-provider-ignition(tf-012) » go version                                                                                                                                 alex@alexs-macbook
go version go1.11.4 darwin/amd64
------------------------------------------------------------
~/workspace/terraform-provider-ignition(tf-012) » make test testacc                                                                                                                          alex@alexs-macbook
==> Checking that code complies with gofmt requirements...
go test -i $(go list ./... |grep -v 'vendor') || exit 1
echo $(go list ./... |grep -v 'vendor') | \
		xargs -t -n4 go test  -timeout=30s -parallel=4
go test -timeout=30s -parallel=4 github.com/terraform-providers/terraform-provider-ignition github.com/terraform-providers/terraform-provider-ignition/ignition
?   	github.com/terraform-providers/terraform-provider-ignition	[no test files]
ok  	github.com/terraform-providers/terraform-provider-ignition/ignition	(cached)
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-ignition	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestIngnitionFileReplace
--- PASS: TestIngnitionFileReplace (0.03s)
=== RUN   TestIngnitionFileAppend
--- PASS: TestIngnitionFileAppend (0.03s)
=== RUN   TestIngnitionFileReplaceNoVerification
--- PASS: TestIngnitionFileReplaceNoVerification (0.03s)
=== RUN   TestIngnitionFileAppendNoVerification
--- PASS: TestIngnitionFileAppendNoVerification (0.03s)
=== RUN   TestIgnitionConfigDisks
--- PASS: TestIgnitionConfigDisks (0.03s)
=== RUN   TestIgnitionConfigArrays
--- PASS: TestIgnitionConfigArrays (0.03s)
=== RUN   TestIgnitionConfigFilesystems
--- PASS: TestIgnitionConfigFilesystems (0.03s)
=== RUN   TestIgnitionConfigFiles
--- PASS: TestIgnitionConfigFiles (0.03s)
=== RUN   TestIgnitionConfigSystemd
--- PASS: TestIgnitionConfigSystemd (0.03s)
=== RUN   TestIgnitionConfigNetworkd
--- PASS: TestIgnitionConfigNetworkd (0.03s)
=== RUN   TestIgnitionConfigUsers
--- PASS: TestIgnitionConfigUsers (0.04s)
=== RUN   TestIgnitionConfigGroupss
--- PASS: TestIgnitionConfigGroupss (0.04s)
=== RUN   TestIngnitionDirectory
--- PASS: TestIngnitionDirectory (0.03s)
=== RUN   TestIngnitionDirectoryInvalidMode
--- PASS: TestIngnitionDirectoryInvalidMode (0.01s)
=== RUN   TestIngnitionDirectoryInvalidPath
--- PASS: TestIngnitionDirectoryInvalidPath (0.01s)
=== RUN   TestIngnitionDisk
--- PASS: TestIngnitionDisk (0.03s)
=== RUN   TestIngnitionDiskInvalidDevice
--- PASS: TestIngnitionDiskInvalidDevice (0.01s)
=== RUN   TestIngnitionDiskInvalidPartition
--- PASS: TestIngnitionDiskInvalidPartition (0.01s)
=== RUN   TestIngnitionFile
--- PASS: TestIngnitionFile (0.04s)
=== RUN   TestIngnitionFileInvalidMode
--- PASS: TestIngnitionFileInvalidMode (0.01s)
=== RUN   TestIngnitionFileInvalidPath
--- PASS: TestIngnitionFileInvalidPath (0.01s)
=== RUN   TestIngnitionFilesystem
--- PASS: TestIngnitionFilesystem (0.05s)
=== RUN   TestIngnitionFilesystemInvalidPath
--- PASS: TestIngnitionFilesystemInvalidPath (0.01s)
=== RUN   TestIngnitionFilesystemInvalidPathAndMount
--- PASS: TestIngnitionFilesystemInvalidPathAndMount (0.01s)
=== RUN   TestIngnitionGroup
--- PASS: TestIngnitionGroup (0.03s)
=== RUN   TestIngnitionLink
--- PASS: TestIngnitionLink (0.03s)
=== RUN   TestIngnitionLinkInvalidPath
--- PASS: TestIngnitionLinkInvalidPath (0.01s)
=== RUN   TestIngnitionNetworkdUnit
--- PASS: TestIngnitionNetworkdUnit (0.03s)
=== RUN   TestIngnitionRaid
--- PASS: TestIngnitionRaid (0.03s)
=== RUN   TestIngnitionRaidInvalidLevel
--- PASS: TestIngnitionRaidInvalidLevel (0.01s)
=== RUN   TestIngnitionRaidInvalidDevices
--- PASS: TestIngnitionRaidInvalidDevices (0.01s)
=== RUN   TestIngnitionSystemdUnit
--- PASS: TestIngnitionSystemdUnit (0.04s)
=== RUN   TestIngnitionSystemdUnitEmptyContentWithDropIn
--- PASS: TestIngnitionSystemdUnitEmptyContentWithDropIn (0.04s)
=== RUN   TestIgnitionSystemdUnit_emptyContent
--- PASS: TestIgnitionSystemdUnit_emptyContent (0.04s)
=== RUN   TestIngnitionSystemUnitInvalidName
--- PASS: TestIngnitionSystemUnitInvalidName (0.01s)
=== RUN   TestIngnitionSystemUnitInvalidContent
--- PASS: TestIngnitionSystemUnitInvalidContent (0.01s)
=== RUN   TestIngnitionUser
--- PASS: TestIngnitionUser (0.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-ignition/ignition	(cached)
------------------------------------------------------------
```

### CODE REVIEW

**Comment by appilon** [comment]
@alexsomesan needed to run and check in `go mod vendor` I took that liberty and ran the tests, still green!

**Comment by alexsomesan** [comment]
Sounds good. I ran them yesterday too. Looks good on my part.
We can merge anytime.

**Comment by seh** [comment]
What does it take to release a fresh version that includes this patch? We'd like to start using Terraform version 0.12.0, but none of the published releases of this provider are suitable for use.

**Comment by alexsomesan** [comment]
A new release needs to be cut. I can do that ASAP.

**Comment by alexsomesan** [comment]
@seh We just released version 1.1.0 with support for TF 0.12

**Comment by seh** [comment]
Thank you! We'll try it today.

**Pull request merged**
